### ISSUE TITLE
use kubelet.cluster_domain configuration

### ISSUE THREAD

**Issue by an-tex** [jaredallard/localizer#28]
Hi,
first of all, great work! I was just about to ditch telepresence ;) I'm missing only one feature:

Currently the services are statically exposed under *.svc.cluster.local .

If you have only one cluster that's fine. But in my case, different clusters have a different [`kubelet.cluster_domain`](https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#introduction) setting. So e.g. when
`kubelet.cluster_domain: staging.myapp.local`
is set, then inside the cluster all services are exposed under *.svc.staging.myapp.local.

It would be great to expose them locally under the same dns. This way I could connect to different environments at the same time and ditch the current "telepresence-disconnect-connect-to-different-env" workflow

Cheers

Edit: I guess if pulling the cluster_domain setting is an issue, a separate command line parameter could work too

**Comment by jaredallard** [comment]
TIL! Didn't know that was an option, I'll see if I can get this done with the v1.2.0 release. Worse case command line argument -- that's ez enough.

**Comment by jaredallard** [comment]
For running multiple instances, I'm not sure how well this'll work in its current form. Right now I'm using go-ipam to allocate IP addresses, but it doesn't actually validate on the host if that IP isn't already allocated (for example, it usually _isn't_ actually allocated since only macOS requires explicit IP aliasing to lo, wsl/linux just let us listen on that address)

**Comment by an-tex** [comment]
> TIL! Didn't know that was an option, I'll see if I can get this done with the v1.2.0 release. Worse case command line argument -- that's ez enough.

It's esp useful when you have different env like local, staging, prod. By having a separate domain for each env you won't by accident run e.g. some test commands against prod ;)

> For running multiple instances, I'm not sure how well this'll work in its current form. Right now I'm using go-ipam to allocate IP addresses, but it doesn't actually validate on the host if that IP isn't already allocated (for example, it usually _isn't_ actually allocated since only macOS requires explicit IP aliasing to lo, wsl/linux just let us listen on that address)

Ah of course. How about another parameter to define custom subnets e.g. 127.0.1.0 ?

**Comment by jaredallard** [comment]
This should be done, please re-open if it's not working as expected!
