### ISSUE TITLE
list doesn't show tunnel status

### ISSUE THREAD

**Issue by goffinf** [jaredallard/localizer#29]
localizer version: **v1.1.1**
platform: **wsl2** (distro ubuntu 20.04.1)

This looks pretty cool so thought I'd give it a go. But hit a couple of problems which most likely are my (mis)understanding ..

Running localizer with no args appears to work ok:

```
sudo -E localizer
INFO[0000] starting GRPC server on '/var/run/localizer.sock'
INFO[0000] creating tunnel for service default/ingress-demo-dom  service="*api.GRPCServiceHandler"
....
```
 ... and sure enough etc/hosts got an entry ...

`127.0.0.2        ingress-demo-dom ingress-demo-dom.default ingress-demo-dom.default.svc ingress-demo-dom.default.svc.cluster ingress-demo-dom.default.svc.cluster.local`

... and I can curl the service successfully in another terminal window:

```
curl http://ingress-demo-dom:8081
<!DOCTYPE html>
<html>
<head>
<title>Hello World</title>
...
```

However, if from the second terminal windows I try to use **list** ...

```
sudo -E localizer list
ERRO[0000] failed to run: localizer instance already running
```

Same thing happens if I run localizer in the background.

If I just run **list** to start with, I get the exact same output as running without any arg, that is, I don't see output like that which appears in your blog post for the list command ...

```
sudo -E localizer list
INFO[0000] starting GRPC server on '/var/run/localizer.sock'
INFO[0000] creating tunnel for service default/ingress-demo-dom  service="*api.GRPCServiceHandler"
```

I note from running with --help that list is not shown as an available command ... has it been removed since you wrote the blog post (that was only 3 days ago) ?

```
sudo -E localizer --help
NAME:
   localizer - A new cli application

USAGE:
   localizer [global options] command [command options] [arguments...]

VERSION:
   1.0.0

COMMANDS:
   expose   expose <namespace/service>
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --context value     Specify Kubernetes context to use [$KUBECONTEXT]
   --log-level value   Set the log level (default: INFO) [$LOG_LEVEL]
   --log-format value  Set the log format (default: TEXT) [$LOG_FORMAT]
   --help, -h          show help (default: false)
   --version, -v       print the version (default: false)
```

What am I missing ?

Kind Regards

Fraser.

**Comment by jaredallard** [comment]
Hello! Thanks for the report! Small note I realized I didn't make in the post, this is actually only available in v1.2.0-beta.1 right now. If you give that release a shot it'll work as expected!
