### ISSUE TITLE
localizer refuses to start after it crashed

### ISSUE THREAD

**Issue by databus23** [jaredallard/localizer#38]
When localizer is force killed or panics the socket file is left at `/var/run/localizer.sock`
Trying to start localizer afterwards then fails until the socket file is manually deleted.
```
ERRO[0000] failed to run: localizer instance already running
```

**Comment by jaredallard** [comment]
Yeah, I'm aware of this. Haven't figured out the best way to handle panics and clean that up. As a short term mitigation was thinking of implementing a ping GRPC method that cam be used to overwrite that file (say, no response in >10s)

**Comment by tvvignesh** [comment]
Yup facing the same issue here after crash.

<img width="278" alt="1" src="https://user-images.githubusercontent.com/1165845/102717653-b11a7580-4309-11eb-95d4-3f76379c1882.PNG">
